//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMovie_DAN.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int ID { get; set; }
        public string Img { get; set; }
        public Nullable<int> IDPhim { get; set; }
    
        public virtual DSPhimBo DSPhimBo { get; set; }
    }
}
