//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMovie_DAN.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebmoviedbEntities : DbContext
    {
        public WebmoviedbEntities()
            : base("name=WebmoviedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<CTTapPhim> CTTapPhims { get; set; }
        public virtual DbSet<DSPhimBo> DSPhimBoes { get; set; }
        public virtual DbSet<DSPhimLe> DSPhimLes { get; set; }
        public virtual DbSet<Nam> Nams { get; set; }
        public virtual DbSet<QuocGia> QuocGias { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<tintucphim> tintucphims { get; set; }
        public virtual DbSet<gioithieu> gioithieux { get; set; }
    }
}
