//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMovie_DAN.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSPhimBo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSPhimBo()
        {
            this.Banners = new HashSet<Banner>();
            this.CTTapPhims = new HashSet<CTTapPhim>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.TaiKhoans1 = new HashSet<TaiKhoan>();
        }
    
        public int ID { get; set; }
        public string TenPhim { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> NamPhatHanh { get; set; }
        public Nullable<int> IDTheLoai { get; set; }
        public string ThoiLuong { get; set; }
        public string Img { get; set; }
        public Nullable<int> MaQG { get; set; }
        public Nullable<int> LuotXem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTapPhim> CTTapPhims { get; set; }
        public virtual Nam Nam { get; set; }
        public virtual QuocGia QuocGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans1 { get; set; }
    }
}
