//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMovie_DAN.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSPhimLe
    {
        public int ID { get; set; }
        public string TenPhim { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> NamPhatHanh { get; set; }
        public Nullable<int> IDTheLoai { get; set; }
        public string ThoiLuong { get; set; }
        public string Img { get; set; }
        public Nullable<int> MaQG { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string Link { get; set; }
    
        public virtual Nam Nam { get; set; }
        public virtual QuocGia QuocGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
